joy_ax0: 1.0 
joy_ax1: 1.0
joy_ax2: 1.0
joy_ax3: 1.0
 
wall_max_yaw:  0.7853 #pi/4  #max angle for safe activate control
wall_max_dist: 3.0          #max dist for safe activate control

d_safe: 1.0        #initial dist from wall to open/close arm
delta_approch: 0.3 #forward dist to move for stable tool contact
Kp_x: 0.2          # p gain for wall dist control
Kp_yaw: 0.3        # p gain for wall yaw control
#Kd_x: 0.0          # d gain for wall dist control
#Kd_yaw: 0.0        # d gain for wall yaw control
K_ff_x_dot: 1.0;  #enable disable traj vel ff
eps_x: 0.001       # error treshold for wall dist control
eps_yaw: 0.001     # error treshold for wall yaw control
vx_cruise: 0.15     #avg lin vel for traj
vx_max: 0.2
vyaw_max: 0.1   